if {isAlive::%player%} is false:
  force player to fly
  hide player from all players
  teleport the player to spawn of "lava"
  apply potion of resistance 255 to the player for 999 days
  apply potion of fire resistance 255 to the player for 999 days
  apply potion of regeneration 5 to the player for 5 seconds
  clear inventory
  give player 1 compass named "&6Right-CLick To Go To Lobby"
    on rightclick holding a compass:
      make the command sender execute "/world world"
