command /playerstatus:
  description: test
  trigger:
    if {isAlive::%player%} is false:
      broadcast "%player% is dead"
    if {isAlive::%player%} is true:
      broadcast "%player% is alive"

on join:
  if world is "lava":
    set {isAlive::%player%} to true

every 3 ticks in "lava":
  loop all players:
    if loop-player's y-coordinate < 7:
      set {isAlive::%loop-player%} to false
    else:
      set {isAlive::%loop-player%} to true
